version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DB_HOST: database
    ports:
      - 8080:80
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin' ,'ping', '-h' ,'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 10

volumes:
  database:
    driver: local
